all:
	g++ \
	-std=gnu++98 \
	-pedantic \
	-I/usr/include \
	-I/usr/lib/jvm/java-8-openjdk/include/ \
	-I/usr/lib/jvm/java-8-openjdk/include/linux \
	-fPIC \
	-O2 \
	-shared \
	net_automatalib_commons_util_lib_NativeGreeter.cpp \
	-o libautomata_greeter.so