/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_automatalib_commons_util_lib_NativeGreeter */

#ifndef _Included_net_automatalib_commons_util_lib_NativeGreeter
#define _Included_net_automatalib_commons_util_lib_NativeGreeter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_automatalib_commons_util_lib_NativeGreeter
 * Method:    greet
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_automatalib_commons_util_lib_NativeGreeter_greet
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
